### ISSUE TITLE
Auto Repair will be one of the main WooCommerce categories or just a default page?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#101]
It was mentioned in the project scope to have **3 main** WooCom categories.
In the other design, "Auto Repairs" was included in the category sidebar, it was stated as well in the project scope.
![image](https://cloud.githubusercontent.com/assets/12888048/12904244/dbf47208-cf08-11e5-8feb-491bd126997e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/12904420/730179ce-cf0a-11e5-8768-f1173af8844a.png)

However, it seems the design for 09-BUN-Auto-repairs.psd is just a simple (default)page and there's no category sidebar as well.
![image](https://cloud.githubusercontent.com/assets/12888048/12904275/3446bb46-cf09-11e5-9990-862236d8370a.png)

**Comment by ravititan** [comment]
Scope has been updated.
