### ISSUE TITLE
Product Single: Button link did not open the correct page. Instead display an Error page

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#114]
![image](https://cloud.githubusercontent.com/assets/12888048/12905635/c3752438-cf13-11e5-9135-d6b50ce1ff4b.png)

**Comment by ravititan** [comment]
@romatitan : I have tested it and the link is opening fine.

**Comment by romatitan** [comment]
Previous: It display an Error page when clicking the related services button.
Current: #162 View Related Services button page link opens in a new tab. Page link should not open in a new tab
