### ISSUE TITLE
FAQ: Responsive error after resizing the browser

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#125]
![image](https://cloud.githubusercontent.com/assets/12888048/12906782/9849e1ee-cf1e-11e5-941d-4356c1333f24.png)

**Comment by ravititan** [comment]
@romatitan : It is working fine for me, Could you please let me know the viewport , device & browser.

**Comment by romatitan** [comment]
283px - 304px
![image](https://cloud.githubusercontent.com/assets/12888048/13415293/919c404a-df94-11e5-9b91-4ad1e56771fc.png)

305px, no space between the title and arrow
![image](https://cloud.githubusercontent.com/assets/12888048/13415296/a030de72-df94-11e5-8348-2c7b447e0b7c.png)
