### ISSUE TITLE
Header: Needs update for the "Refer a Friend" section of the header

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#13]
![image](https://cloud.githubusercontent.com/assets/12888048/12670430/58ded47a-c6a3-11e5-9cfc-7a2344a57ee5.png)

![image](https://cloud.githubusercontent.com/assets/12888048/12670432/5cdd4ad4-c6a3-11e5-9360-a73eb11c89a4.png)

**Comment by ravititan** [comment]
@romatitan : So far I haven't  received any update on this from Bernard.

**Comment by romatitan** [comment]
Need Feedback.

**Comment by ravititan** [comment]
Here is the comment from Bernard : 
"Currently waiting for a reply from the PM responsible regarding the status of the designs, but I already asked Ross about it and nobody could find the designs in question. As Fred is on leave until the 29th, I second the recommendation that this functionality be pushed to pre-live."
