### ISSUE TITLE
Header: Search icon has no function

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#14]
![image](https://cloud.githubusercontent.com/assets/12888048/12670699/7265499a-c6a5-11e5-98e6-c5c55ed22722.png)

**Comment by ravititan** [comment]
@romatitan : There was no mention about the search functionality/nature neither on scope doc nor in the design.
Please let me know what this has to be

**Comment by romatitan** [comment]
In the given design, we only have "Search" magnifying-glass icon.
Here's a possible implementation.
A search field will appear when the magnifying glass icon was clicked.
It should have a search function and a page that will display the search results.

Please check the screenshot below for your reference.
![image](https://cloud.githubusercontent.com/assets/12888048/13340479/88ab36fc-dc6b-11e5-8378-16f508091bfe.png)
![image](https://cloud.githubusercontent.com/assets/12888048/13340582/5f31b872-dc6c-11e5-9cc3-73eee59970d5.png)
