### ISSUE TITLE
Product: Truncated product title

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#161]
![image](https://cloud.githubusercontent.com/assets/12888048/13388675/e6a48d42-defc-11e5-8d4c-4fe60ae8acbc.png)

**Comment by ravititan** [comment]
![product-screen](https://cloud.githubusercontent.com/assets/13450891/13776865/74a091aa-ead2-11e5-8454-d6146dd5604d.jpg)

**Comment by romatitan** [comment]
Kindly check on Chrome and Opera browser.
