### ISSUE TITLE
Lead-ins: Not responsive

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#165]
![image](https://cloud.githubusercontent.com/assets/12888048/12906431/2030be56-cf1b-11e5-93fb-3aa470f5e094.png)

![image](https://cloud.githubusercontent.com/assets/12888048/12906435/231e707c-cf1b-11e5-9612-97e9ac4bce90.png)

**Comment by romatitan** [comment]
**Leadins are not responsive.320px - 280px**

![image](https://cloud.githubusercontent.com/assets/12888048/13595012/32c84924-e543-11e5-8111-f892ba20e4b7.png)

**Comment by ravititan** [comment]
I have tested and it is working fine her, till 992 it is showing 4 leadins in a row and 2 leadins in a row after 992.

**Comment by romatitan** [comment]
It seems the lead-ins were stretched vertically.
Kindly check this link.
http://screencast.com/t/uWbkLVvYN0
