### ISSUE TITLE
General - Inner pages: Upper Pre-Footer responsive errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#169]
![image](https://cloud.githubusercontent.com/assets/12888048/13416727/cf3b36c6-df9f-11e5-8a01-2aa194acd4d9.png)
![image](https://cloud.githubusercontent.com/assets/12888048/13416741/e34da5f4-df9f-11e5-8281-5adba3e47300.png)
![image](https://cloud.githubusercontent.com/assets/12888048/13416753/f0733ce4-df9f-11e5-9cbb-db253b71e92c.png)
![image](https://cloud.githubusercontent.com/assets/12888048/13416757/f3222c8e-df9f-11e5-94c9-72f85fe5420f.png)

**Comment by romatitan** [comment]
Upper Pre-Footer is not responsive.
320px- 280px
1200px - 992px
![image](https://cloud.githubusercontent.com/assets/12888048/13595273/f4796df4-e544-11e5-889c-ea3e66908592.png)

**Comment by ravititan** [comment]
I have tested in Mozilla and Chrome it is working fine from 1200px to 992px

**Comment by romatitan** [comment]
http://screencast.com/t/uWbkLVvYN0
