### ISSUE TITLE
Admin - Banner: <br/> is not allowed to use in post tite

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#25]
![image](https://cloud.githubusercontent.com/assets/12888048/12737495/02ccee5c-c994-11e5-8439-fef7cda19c24.png)

**Comment by ravititan** [comment]
@romatitan : I have discussed with Salman, We have used <br> tag in previous projects as well, Could you please cross check with your TL.

**Comment by romatitan** [comment]
Can you provide a specific project that use **break** tag in post title.
**Span** tag is allowed, however, we don't allow break tag so far.

**Comment by ravititan** [comment]
@romatitan : http://martins-produce.stage.titanweb.com.au/
This is the site which is having a break tag in title, It might have been removed during pre-live tasks.

**Comment by romatitan** [comment]
break tag removed
