### ISSUE TITLE
Lead-ins: Incorrect background layout and style

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#33]
![image](https://cloud.githubusercontent.com/assets/12888048/12738196/a344ff00-c999-11e5-9f3c-998aed7c1054.png)

**Comment by romatitan** [comment]
Kindly check again.

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/13589077/0f25f742-e510-11e5-9248-a5cc9e1c3b34.png)

**Comment by ravititan** [comment]
It is working fine here could you please let me know on which ports you are checking it.

**Comment by romatitan** [comment]
Full desktop view, in All browser
![image](https://cloud.githubusercontent.com/assets/12888048/13908899/f3e0a4d6-ef47-11e5-963b-c5729328bd09.png)
