### ISSUE TITLE
Lead-ins: The 1st four items in order should be display in front end

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#36]
![image](https://cloud.githubusercontent.com/assets/12888048/12738634/6e0052f0-c99d-11e5-8278-f38d1a27fd1a.png)

**Comment by ravititan** [comment]
@romatitan : 
As per the knowledge base , Posts order are by menu_order according to their title.
https://knowledgebase.titanweb.com.au/implementation/standard-pages/custom-posts

**Comment by romatitan** [comment]
Yes. Ensure that they **can be** arranged under the Order Attributes (meaning it is optional if the user wants to use the "Re-Order").
But if the user did not use the "Re-Order" or Order attributes, the** first 4 newly added lead-ins** should be display.

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/13589198/f83e8ac0-e510-11e5-96e3-1a5d2c3b6015.png)

**Comment by ravititan** [comment]
If there is no page link selected the leadin will not be displayed.
