### ISSUE TITLE
Admin - Homepage:<br> tag is not allowed to use in page title

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#39]
![image](https://cloud.githubusercontent.com/assets/12888048/12739051/d144fa20-c9a0-11e5-8732-ff022edef8fe.png)

**Comment by ravititan** [comment]
@romatitan : I have discussed with Salman, We have used <br> tag in previous projects as well, Could you please cross check with your TL.

**Comment by romatitan** [comment]
Can you provide a specific project that use break tag in **page** title.
So far, we don't allow break tag.

**Comment by ravititan** [comment]
@romatitan : http://martins-produce.stage.titanweb.com.au/
This is the site which is having a break tag in title, It might have been removed during pre-live tasks.

**Comment by romatitan** [comment]
break tag removed
