### ISSUE TITLE
Admin - Homepage: Incorrect implementation

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#40]
1. **tab section was not implemented**
![image](https://cloud.githubusercontent.com/assets/12888048/12739071/f530d882-c9a0-11e5-8957-31d244179418.png)

2. Welcome section description should have an **ACF WYSIWYG**. 
**Do not use**  the **page default wysiwyg**. **Remove** the **default wysiwyg**.
![image](https://cloud.githubusercontent.com/assets/12888048/12739119/6f52948e-c9a1-11e5-9fcc-c23454665f67.png)

**Comment by ravititan** [comment]
@romatitan : Discussed with @bernardtitan he said to skip this ,it's not possible to put the default page title and content in a tab so we'll skip that

**Comment by romatitan** [comment]
Pending issue. We will clarify this first.
