### ISSUE TITLE
General: Incosistent h1 font size. It should be consistent in all pages. Use 36px for h1

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Bunbury-Batteries#66]
1. Design Error for Homepage
![image](https://cloud.githubusercontent.com/assets/12888048/12777189/3070edf6-ca96-11e5-96ed-76e036192ec3.png)

2. Inner pages H1 was set to 28px.
![image](https://cloud.githubusercontent.com/assets/12888048/12777198/4023d1b4-ca96-11e5-95a1-efdd82039f48.png)

**Comment by ravititan** [comment]
@romatitan : I have fixed the 2. point as the first point has been implemented as per the psd.

**Comment by romatitan** [comment]
For the homepage, kindly set the h1 heading font size to 36px to be consistent with the inner pages.

**Comment by romatitan** [comment]
For the homepage, kindly set the h1 heading font size to 36px to be consistent with the inner pages.
![image](https://cloud.githubusercontent.com/assets/12888048/13589446/ef17f218-e512-11e5-9551-8ff5617251b4.png)
